apiVersion: v1
kind: Pod
metadata:
  name: namenode
  namespace: flux
  labels:
    app: flux-nn
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_"}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hostNetwork: false
  hostPID: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: namenode
      replicas: 1
      image: {{ .Values.image.namenode }}
      hostname: namenode
      ports:
        - containerPort: 50070
        - containerPort: 8020
      env:
        - name: CLUSTER_NAME
          value: flux-cluster
      envFrom:
        - configMapRef:
            name: hadoop-cm
      volumeMounts:
        - name: namenode-volume
          mountPath: /hadoop/dfs
  volumes:
    - name: namenode-volume
      persistentVolumeClaim:
        claimName: namenode-volume-namenode-0
  nodeSelector:
    hdfs-namenode-selector: hdfs-namenode  

