sudo: required

language: python

env:
  - CHANGE_MINIKUBE_NONE_USER=true

services:
  - docker

before_script:
  # install minikube
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.2/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - minikube config set WantReportErrorPrompt false
  - sudo minikube start --vm-driver=none --kubernetes-version=v1.9.0
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
  - kubectl cluster-info
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
  - chmod 700 get_helm.sh
  - sudo ./get_helm.sh
  - helm init

script:
  - ./bin/flux build
  # - ./deploy/docker/docker_build_ros_gpu.sh
  # - ./deploy/docker/docker_build_gpu.sh
  - ./bin/flux start
  - sleep 10 # TODO: avoid sleep
  - ./bin/flux ps
  # TODO: execute all notebooks
  - ./bin/flux stop
  - ./bin/flux purge
