#!/usr/bin/env bash

NODES=$(kubectl get nodes -o jsonpath='{.items..metadata.name}')
NODES_CNT=$(echo "${NODES}" | tr ' ' '\n' | wc -l | xargs echo -n)
NAMENODES=$(kubectl get nodes -o jsonpath="{.items[?(@.metadata.labels['hdfs-namenode-selector'])]..metadata.name}" | tr ' ' ',')
NAMENODES_CNT=$(echo "${NAMENODES}" | tr ',' '\n' | wc -l | xargs echo -n)
DATANODES=$(kubectl get nodes -o jsonpath="{.items[?(@.metadata.labels['hdfs-datanode-selector'])]..metadata.name}" | tr ' ' ',')
DATANODES_CNT=$(echo "${DATANODES}" | tr ',' '\n' | wc -l | xargs echo -n)

# echo "Nodes: ${NODES}"
# echo "Namenodes: ${NAMENODES}"
# echo "DataNodes: ${DATANODES}"

echo -n "--set flux.datanodes_cnt=${DATANODES_CNT} --set flux.datanodes={${DATANODES}} --set flux.namenodes={${NAMENODES}}"
