apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: flux-ros-hadoop
  name: flux-ros-hadoop
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/flux-ros-hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flux-ros-hadoop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flux-ros-hadoop
    spec:
      containers:
      - image: flux/ros_hadoop_k8s:0.1
        imagePullPolicy: IfNotPresent
        name: flux-ros-hadoop
        ports:
        - containerPort: 8000
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
